//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakipOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public Kategoriler()
        {
            this.Markalar = new HashSet<Markalar>();
            this.Ürün = new HashSet<Ürün>();
        }
    
        public int ID { get; set; }
        public string Kategori { get; set; }
        public string Açıklama { get; set; }
    
        public virtual ICollection<Markalar> Markalar { get; set; }
        public virtual ICollection<Ürün> Ürün { get; set; }
    }
}
