//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakipOtomasyonu.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_StokTakipEntities : DbContext
    {
        public MVC_StokTakipEntities()
            : base("name=MVC_StokTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Birimler> Birimler { get; set; }
        public DbSet<Kategoriler> Kategoriler { get; set; }
        public DbSet<Markalar> Markalar { get; set; }
        public DbSet<Müşteriler> Müşteriler { get; set; }
        public DbSet<Satışlar> Satışlar { get; set; }
        public DbSet<Sepet> Sepet { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Ürün> Ürün { get; set; }
    }
}
